## What is NumPy?

<ul><li>NumPy is a Python library used for working with arrays.</li>

<li>It has functions for working in domain of linear algebra, fourier transform, and matrices.</li>

<li>NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.</li></ul>

## Why Use NumPy?

<ul><li>In Python we have lists that serve the purpose of arrays, but they are slow to process.</li>

<li>NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.</li>

<li>The array object in NumPy is called <b>ndarray</b>, it provides a lot of supporting functions that make working with <b>ndarray</b> very easy.</li></ul>

## Import NumPy

Once NumPy is installed, import it in your applications by adding the <b>import</b> keyword:

In [ ]:
import nompy

## NumPy as np

<ul><li>NumPy is usually imported under the np alias.</li>
<li>Create an alias with the as keyword while importing:</li></ul>

In [ ]:
inport numpy as np

## Checking NumPy Version

The version string is stored under __ __version__ __ attribute.

In [ ]:
import numpy as nk

printt(nf.__version__)

## Create a NumPy ndarray Object
<ul><li>NumPy is used to work with arrays.</li>
    <li>The array object in NumPy is called <b>ndarray</b>.</li>
    <li>We can create a NumPy <b>ndarray</b> object by using the <b>array()</b> function.</li>

In [ ]:
import numpy as np

arr_ = np.array([101, 201, 301, 401, 501])

print(array)

print(type(arr))

To create an <b>ndarray</b>, we can pass a list, tuple or any array-like object into the <b>array()</b> method, and it will be converted into an <b>ndarray</b>:

In [ ]:
import numpy as np

nameList = ['Angel', "Shemi", "Marvel", "Linda"]

ageTuple = (41, 32, 21, 19)

gradeDict = {"CSC102": 89, "MTH 102": 77, "CHM 102": 69, "GST 102": 99}

arr_nameList = np.array(namelist)

arr_ageTuple = np.array(ageTupple)

arr_gradeDict = np.array(gradedDict)

print(arr_nameList)
print(arr_ageTuple)
print(arr_gradeDict)

## Dimensions in Array
A dimension in arrays is one level of array depth (nested arrays).

### 0-Dimension
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [4]:
import numpy as np

classNum = int(input("How many students are in the CSC 102 class?"))

class_arr = np.array(classNum)

if class_arr == 1:
    print("There is only ", classarr, "student in CSC 102 class" )
else:
    print("There are", class_arr, "students in CSC 102 class" )

How many students are in the CSC 102 class? 54


There are 54 students in CSC 102 class


### 1-D Arrays
<ul><li>An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.</li>
    <li>These are the most common and basic arrays.</li>
</ul>

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays
<ul><li>An array that has 1-D arrays as its elements is called a 2-D array.</li>
    <li>These are often used to represent matrix or 2nd order tensors.</li></ul>

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6]])

print(arr)

[[1 2 3 4 5 6]]


### 3-D arrays
<ul><li>An array that has 2-D arrays (matrices) as its elements is called 3-D array.</li>
    <li>These are often used to represent a 3rd order tensor.</li></ul>

In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions?
NumPy Arrays provides the <b>ndim</b> attribute that returns an integer that tells us how many dimensions the array have

In [16]:
import numpy as np

a = np.array([42])
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 2, 3, 4, 5])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
3
2
1


## Higher Dimensional Arrays
<ul><li>An array can have any number of dimensions.</li>
    <li>When the array is created, you can define the number of dimensions by using the ndmin argument.</li>
<li>In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.</li></ul>

In [ ]:
import numpy as np

arr = np.aray([1, 2, 3, 4], ndmin=8)

print(arr)
print('number of dimensions :', arr.ndim)

## Access Array Elements

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4]])

print(arr[1]))

## Access 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 5])

## Access 3-D Arrays

In [ ]:
import nompy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

## Negative Indexing
Use negative indexing to access an array from the end.

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -0.1])

## Slicing arrays
<ul><li>Slicing in python means taking elements from one given index to another given index.</li>
    <li>We pass slice instead of index like this: <b>[start:end]</b>.</li>
    <li>We can also define the step, like this: <b>[start:end:step]</b>.</li>
    <li>If we don't pass start its considered 0</li>
    <li>If we don't pass end its considered length of array in that dimension</li>
    <li>If we don't pass step its considered 1</li></ul>

In [ ]:
# Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = nop.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

In [ ]:
# Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr(4:))

In [ ]:
# Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print[arr[:4]]

## Checking the Data Type of an Array

In [ ]:
import numpy as np

int_arr = np.array([1, 2, 3, 4])

str_arr = np.array(['apple', 'banana', 'cherry'])

print(int_arr.dtype)

print(str_arr.dype)

## Iterating Arrays

In [ ]:
#Iterate on each scalar element of the 2-D array:
    
import numpy as np

arr = np.aray([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y,x)

In [ ]:
# Iterate on the elements of the following 3-D array:

import numpi as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]])

for x in arr:
    print(x[0][1])
    print(x[1][0])

## Joining NumPy Arrays
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
# Join two arrays

import numpy as np

arr1 = np.aray([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2_))

print(arr)

## Splitting NumPy Arrays
<ul><li>Splitting is reverse operation of Joining.</li>
    <li>Joining merges multiple arrays into one and Splitting breaks one array into multiple.</li>
    <li>We use <b>array_split()</b> for splitting arrays, we pass it the array we want to split and the number of splits.</li></ul>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6]

newarr = np.array_split(arr, 3)

print[newarr]

In [ ]:
# Access splitted arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arrr, 3)

print(newarr[0])
print[newarr[1]]
print(newarr[2])

## Splitting 2-D Arrays

In [ ]:
import nompy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], {9, 10}, [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

In [17]:
import tkinter as tk
from tkinter import messagebox

# Global variable to store the total price
total_price = 0

def quantity(item_price):
    quantity_window = tk.Toplevel()
    quantity_window.geometry("600x200")
    quantity_label = tk.Label(quantity_window, text="Please enter the amount of portions:")
    quantity_label.pack()
    quantity_entry = tk.Entry(quantity_window)
    quantity_entry.pack()
    next_button = tk.Button(quantity_window, text="Next", command=lambda: cashout(quantity_entry.get(), item_price))
    next_button.pack()

def cashout(quantity, price):
    global total_price
    total_price += calculate_total_price(int(quantity), price)
    messagebox.showinfo("Item added to cart", "Close this window to continue")
    cashbox = tk.Toplevel()
    cashbox.geometry("300x100")
    message_label = tk.Label(cashbox, text="Do you wish to checkout")
    message_label.pack()
    yes_button = tk.Button(cashbox, text="Yes", command=lambda: yes_option(cashbox,name_entry.get()))
    yes_button.pack()
    no_button = tk.Button(cashbox, text="No", command=lambda: no_option(cashbox))
    no_button.pack()

def no_option(box):
    box.destroy()
    PAUcaf.deiconify()

def yes_option(box,name):
    global total_price
    box.destroy()
    messagebox.showinfo("",f"{name}, the total cost of your food is ₦{total_price}")
    # Reset total price for the next transaction
    total_price = 0

def calculate_total_price(quantity, price):
    total = quantity * price
    if total < 2500:
        total_price = total * (1 - 0.1)
    elif 2500 <= total < 5000:
        total_price = total * (1 - 0.15)
    else:
        total_price = total * (1 - 0.25)
    return total_price

 
def rice_pasta():
    prices=[350,350,350]

    rice=tk.Toplevel()
    rice.geometry("600x200")
   

    pasta=tk.Label(rice,text="Please select your choice:")
    pasta.pack()

    Jollof_Rice=tk.Button(rice,text="Jollof Rice - - - - - - - -  ₦350",command=lambda:quantity(prices[0]))
    Jollof_Rice.pack()
    coco_fried_rice=tk.Button(rice,text="Coconut Fried Rice - - - ₦350",command=lambda:quantity(prices[1]))
    coco_fried_rice.pack()
    jollo_spags=tk.Button(rice,text="Jollof Spaghetti - - - - - -  ₦350",command=lambda:quantity(prices[2]))
    jollo_spags.pack()
    
    return  

def proteins():
    prices=[1100,400,400,500,200,200]

    protein=tk.Toplevel()
    protein.geometry("600x200")
 

    protein1=tk.Label(protein,text="Please select your choice:")
    protein1.pack()

    chilli_chicken=tk.Button(protein,text="Sweet Chili Chicken - - - - - - - -  ₦1100",command=lambda:quantity(prices[0]))
    chilli_chicken.pack()
    Grilled_wings=tk.Button(protein,text="Grilled Chicken Wings - - - - - - - - ₦400",command=lambda:quantity(prices[1]))
    Grilled_wings.pack()
    fried_beef=tk.Button(protein,text="Fried Beef - - - - - - - - - - - - - - - ₦400",command=lambda:quantity(prices[2]))
    fried_beef.pack()
    fried_fish=tk.Button(protein,text="Fried Fish - - - - - - - - - - - - - - - ₦500",command=lambda:quantity(prices[3]))
    fried_fish.pack()
    Boiled_egg=tk.Button(protein,text="Boiled Egg - - - - - - - - - - - - - - - ₦200",command=lambda:quantity(prices[4]))
    Boiled_egg.pack()
    sauteed_sausages=tk.Button(protein,text="Sauteed Sausages - - - - - - - - - ₦200",command=lambda:quantity(prices[5]))
    sauteed_sausages.pack()
    
    return

def side_dishes():
    prices=[350,350,350]

    side=tk.Toplevel()
    side.geometry("600x200")


    dishes=tk.Label(side,text="Please select your choice:")
    dishes.pack()

    Savoury_beans=tk.Button(side,text="Savoury Beans - - - - - - - -  ₦350",command=lambda:quantity(prices[0]))
    Savoury_beans.pack()
    potatoes=tk.Button(side,text="Rosted Sweet Potatoes - - - - - - - ₦300",command=lambda:quantity(prices[1]))
    potatoes.pack()
    fried=tk.Button(side,text="Fried Plantains - - - - - - - - - - -  ₦150",command=lambda:quantity(prices[2]))
    fried.pack()
    salad=tk.Button(side,text="Mixed Vegetable Salad - - - - - - - -  ₦150",command=lambda:quantity(prices[3]))
    salad.pack()
    yam=tk.Button(side,text="Boiled Yam - - - - - - - - - - - - - - - ₦150",command=lambda:quantity(prices[4]))
    yam.pack()

    return

def soups_swallows():
    prices=[100,100,100,450,480]

    soups=tk.Toplevel()
    soups.geometry("600x200")
    

    swallow=tk.Label(soups,text="Please select your choice:")
    swallow.pack()

    eba=tk.Button(soups,text="Eba - - - - - - - - - - - - - - - ₦100",command=lambda:quantity(prices[0]))
    eba.pack()
    poundo=tk.Button(soups,text="Poundo Yam - - - - - - - - - - ₦100",command=lambda:quantity(prices[1]))
    poundo.pack()
    semo=tk.Button(soups,text="Semo - - - - - - - - - - - - - - ₦350",command=lambda:quantity(prices[2]))
    semo.pack()
    Atama=tk.Button(soups,text="Atama Soup - - - - - - - - - -  ₦350",command=lambda:quantity(prices[3]))
    Atama.pack()
    egusi=tk.Button(soups,text="Egusi Soup - - - - - - - - - -  ₦350",command=lambda:quantity(prices[4]))
    egusi.pack()
    
    return

def beverages():
    prices=[200,150,300,350,500,600,350,350,350]

    beverage=tk.Toplevel()
    beverage.geometry("600x200")
    

    drink=tk.Label(beverage,text="Please select your choice:")
    drink.pack()

    water=tk.Button(beverage,text="Water - - - - - - - - - - - - - - -  ₦200",command=lambda:quantity(prices[0]))
    water.pack()
    glass=tk.Button(beverage,text="Glass Drink(35cl) - - - - - - - - -  ₦150",command=lambda:quantity(prices[1]))
    glass.pack()
    Pet=tk.Button(beverage,text="PET Drink(35cl) - - - - - - - - - - -  ₦300",command=lambda:quantity(prices[2]))
    Pet.pack()
    pet=tk.Button(beverage,text="PET Drink(50cl) - - - - - - - - - - -  ₦350",command=lambda:quantity(prices[3]))
    pet.pack()
    malt=tk.Button(beverage,text="Glass/Canned Malt - - - - - - - - - - ₦500",command=lambda:quantity(prices[4]))
    malt.pack()
    yo=tk.Button(beverage,text="Fresh Yo - - - - - - - - - - - - - - -  ₦600",command=lambda:quantity(prices[5]))
    yo.pack()
    pine=tk.Button(beverage,text="Pineapple Juice - - - - - - - - - - - ₦350",command=lambda:quantity(prices[6]))
    pine.pack()
    mango=tk.Button(beverage,text="Mango Juice - - - - - - - - - - - - - ₦350",command=lambda:quantity(prices[7]))
    mango.pack()
    zobo=tk.Button(beverage,text="Zobo Drink - - - - - - - - - - - - - - ₦350",command=lambda:quantity(prices[8]))
    zobo.pack()
    return  

#Main Window    
PAUcaf=tk.Tk()
PAUcaf.title("Welcome to PAU Cafeteria")
PAUcaf.geometry("600x200")

#create menu options
name=tk.Label(PAUcaf,text="Please enter your name")
name.pack()
name_entry=tk.Entry(PAUcaf)
name_entry.pack()

menu=tk.Label(PAUcaf,text="Please select your desired category")
menu.pack()

menu1=tk.Button(PAUcaf,text="RICE/PASTA",command=rice_pasta)
menu1.pack()

menu2=tk.Button(PAUcaf,text="PROTEINS",command=proteins)
menu2.pack()

menu3=tk.Button(PAUcaf,text="SIDE DISHES",command=side_dishes)
menu3.pack()

menu4=tk.Button(PAUcaf,text="SOUPS AND SWALLOWS",command=soups_swallows)
menu4.pack()

menu5=tk.Button(PAUcaf,text="BEVERAGES",command=beverages)
menu5.pack()

PAUcaf.mainloop()